services:
  resume-backend:
    build: 
      context: ./src/lib/server
      dockerfile: Dockerfile.backend
    container_name: resume-backend
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=production
    restart: always
    volumes:
      - ./server:/app
    networks:
      - resume-network

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    container_name: resume-frontend
    ports:
      - "80:80"
    depends_on:
      - resume-backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge